server:
  port: 9000
  servlet:
    context-path: /auth
spring:
  application:
    name: springboot-security
  datasource:
    url: jdbc:mysql://localhost:3306/auth_center?characterEncoding=utf-8
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      initial-size: 10
      max-active: 20
      min-idle: 8
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhou.*.entity
  configuration:
    cache-enabled: true
    call-setters-on-nulls: on
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
