spring:
  datasource:
    url: jdbc:mysql://47.111.103.228:3306/zd_room?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zdroom
    password: Admin-123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      initial-size: 10
      max-active: 20
      min-idle: 8
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.qky.*.entity
  configuration:
    cache-enabled: false
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
