spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_test?characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      initial-size: 10
      max-active: 20
      min-idle: 8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: admin123
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 5000
